[TEST] automate chain specs
paseo-network/runtimes pull request #132
Opened 2024-09-11 11:46 UTC by raynaudoe

2024-09-11 20:20 UTC, al3mart commented on .github/workflows/generate-chain-specs.yaml
> +          toolchain: 1.79.0
Let's use 1.77

2024-09-11 20:20 UTC, al3mart commented on .github/workflows/generate-chain-specs.yaml
> +        run: rustup component add rust-src --toolchain 1.79.0-x86_64-unknown-linux-gnu
Same than above. Let's use 1.77 as the [fellowship does](https://github.com/polkadot-fellows/runtimes/releases/tag/v1.3.2).

2024-09-17 12:22 UTC, raynaudoe commented on .github/workflows/generate-chain-specs.yaml
> +            "coretime-paseo-local"
These ones will be removed

2024-09-18 10:54 UTC, al3mart requested changes
Left a comment with a small nit. Aside from that it looks good.

2024-09-18 10:54 UTC, al3mart commented on .github/workflows/generate-chain-specs.yaml
> +            "coretime-paseo"
These two can be removed.

2024-09-18 11:18 UTC, raynaudoe commented on .github/workflows/generate-chain-specs.yaml
> +            "coretime-paseo"
Done!

2024-09-26 13:16 UTC, al3mart approved these changes

2024-09-26 13:19 UTC, merged