Live Asset Hub spec for Paseo
paseo-network/runtimes pull request #54
Opened 2024-03-14 21:57 UTC by al3mart

2024-03-14 22:44 UTC, hbulgarini requested changes
@al3mart shouldn't this PR target the branch hb-feat-add-asset-bridge-hubs instead of main? I mean i would split the PRs and point everything to this final PR: https://github.com/paseo-network/runtimes/pull/44

2024-03-14 22:47 UTC, al3mart commented
Done, though I guess AssetHub might be running before the branch is merged.

2024-03-15 07:15 UTC, hbulgarini approved these changes

2024-03-15 12:56 UTC, carlosala approved these changes

2024-03-22 10:18 UTC, merged