Adds BridgeHub
paseo-network/runtimes pull request #95
Opened 2024-07-16 13:50 UTC by claravanstaden

- [ ] Compiles
- [ ] Test Pass
- [ ] Integration tests pass

2024-07-18 15:33 UTC, al3mart requested changes

2024-07-18 16:29 UTC, hbulgarini commented on Cargo.toml
> +paseo-emulated-chain = { path = "integration-tests/emulated/chains/relays/paseo"}
True, it seems to be no chain folder

2024-07-18 17:42 UTC, claravanstaden commented on Cargo.toml
> +paseo-emulated-chain = { path = "integration-tests/emulated/chains/relays/paseo"}
🤔 How so?

2024-07-18 18:54 UTC, claravanstaden commented on Cargo.toml
> +paseo-emulated-chain = { path = "integration-tests/emulated/chains/relays/paseo"}
Ah whoops, was ignored by .gitignore. Added in https://github.com/paseo-network/runtimes/pull/95/commits/369aba51b787448ef2706006151452df6ed1d253.

2024-07-19 15:21 UTC, hbulgarini approved these changes
This PR looks good to me. I will leave the confirmation to @al3mart that we are good to go.

2024-07-22 08:03 UTC, al3mart approved these changes
LGTM

2024-07-22 08:03 UTC, merged